apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-path: aggregates/local-cluster/replace
  name: local-cluster-aggregates-replace
spec:
  channel: mgmt-channel-git-openshift-gitops-rhacm/openshift-gitops-rhacm
  placement:
    placementRef:
      name: local-cluster
      kind: PlacementRule
