apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-cluster-config
spec:
  destination:
    name: local-cluster
  project: local-cluster
  source:
    path: aggregates/local-cluster-cluster-config
    repoURL: https://github.com/noseka1/multicluster-management-rhacm-argocd
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
