apiVersion: v1
kind: ExternalSecret
metadata:
  name: mycluster-ssh-private-key
  namespace: mycluster
spec:
  backendType: vault
  kvVersion: 2
  template:
    type: Opaque
  data:
  - name: ssh-privatekey
    key: kv/data/mycluster
    property: ssh-privatekey
