apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mycluster-aws-creds
  namespace: mycluster
spec:
  backendType: vault
  kvVersion: 2
  template:
    type: Opaque
  data:
  - name: aws_access_key_id
    key: kv/data/mycluster
    property: aws_access_key_id
  - name: aws_secret_access_key
    key: kv/data/mycluster
    property: aws_secret_access_key
