apiVersion: v1
kind: ExternalSecret
metadata:
  name: mycluster-install-config
  namespace: mycluster
spec:
  backendType: vault
  kvVersion: 2
  template:
    type: Opaque
  data:
  - name: install-config.yaml
    key: kv/data/mycluster
    property: install-config.yaml
