apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mycluster-pull-secret
  namespace: mycluster
spec:
  backendType: vault
  kvVersion: 2
  template:
    type: kubernetes.io/dockerconfigjson
  data:
  - name: .dockerconfigjson
    key: kv/data/mycluster
    property: pull_secret
