apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm-kubernetes-external-secrets
  namespace: mgmt-channel-helm-kubernetes-external-secrets
spec:
  type: HelmRepo
  pathname: https://external-secrets.github.io/kubernetes-external-secrets
