apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: external-secrets-deployable
spec:
  channel: mgmt-channel-ns-external-secrets-deployable/ns-external-secrets-deployable
  placement:
    placementRef:
      name: mycluster
      kind: PlacementRule
