apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mycluster
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: mycluster
    server: '*'
  sourceRepos:
  - '*'
